# 应用名称
# 应用服务 WEB 访问端口
server:
  port: 83
  application:
    name: webcloud-service-provider

# Dubbo 消费端订阅服务端的应用名，多个服务提供者用逗号分隔
# 这里订阅"自己"，会被忽略掉，请根据实际情况添加
#dubbo.cloud.subscribed-services=webcloud-parent

# dubbo 服务扫描基准包
dubbo:
  ## dubbo 协议
  protocol:
    id: dubbo
    name: dubbo
# dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: 20880
  scan:
    base-packages: com.webcloud
  application:
    name: webcloud-service-provider
  registry:
    address: zookeeper://127.0.0.1:2181


# 数据库驱动：
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
# 数据源名称
    name: com.alibaba.druid.pool.DruidDataSource
# 数据库连接地址
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC
# 数据库用户名&密码：
    username: root
    password: root

# Redis数据库索引（默认为0）
redis:
  database: 0
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接密码（默认为空）
  password:
  # 连接池最大连接数（使用负值表示没有限制）
  jedis:
    pool:
      max-active: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 2000
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
  # 连接超时时间（毫秒）
  timeout: 1000

  # thymeleaf静态资源配置
  # 默认路径
thymeleaf:
  prefix: classpath:/templates/
  # 后缀
  suffix: .html
  # 模板格式
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
  cache: false


logging:
  level: warn





