# 应用名称
# 应用服务 WEB 访问端口
server:
  port: 81
  servlet:
    application-display-name: webcloud-service-provider

# Dubbo 消费端订阅服务端的应用名，多个服务提供者用逗号分隔
# 这里订阅"自己"，会被忽略掉，请根据实际情况添加
#dubbo.cloud.subscribed-services=webcloud-parent

# dubbo 服务扫描基准包
dubbo:
  ## dubbo 协议
  protocol:
    id: dubbo
    name: dubbo
# dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: 20880
  scan:
    base-packages: com.webcloud.service
  application:
    name: webcloud-service-provider
  registry:
    address: zookeeper://127.0.0.1:2181


# 数据库驱动：
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
# 数据源名称
    name: com.alibaba.druid.pool.DruidDataSource
# 数据库连接地址
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC
# 数据库用户名&密码：
    username: root
    password: root

# Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 2000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000

# thymeleaf静态资源配置
  # 默认路径
  thymeleaf:
    prefix: classpath:/templates/
  # 后缀
    suffix: .html
  # 模板格式
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

thymeleaf_pagepath: ../../../../webcloud-frontend/src/main/resource/templates


#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  #指定Mybatis的实体目录
  type-aliases-package: com.webcloud.dao



#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.webcloud.pojo
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
#      field-strategy: not_empty
      #驼峰下划线转换
#      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
      refresh: true
  # 原生配置
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
logging:
  level: warn





